name: Lint

on:
  pull_request:
  push:

permissions: { } # ie none.

jobs:
  check:
    name: Check
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: shellcheck --enable=all --norc *.sh
      - run: yamllint .
